"use client";

import React, { useEffect, useRef, useState } from "react";
import { suits, SuitLayer } from "../data/options";
import { SuitState } from "../hooks/useSuitConfigurator";
import { getTransparentCdnBase } from "../utils/backend";
import { getBackendBase } from "../utils/backend";

/* =====================================================================================
   CDN helpers (ostaju jer maske i strukturalni sprite-ovi su i dalje iz transparent/)
===================================================================================== */
const cdnTransparent = getTransparentCdnBase();

const fileBase = (p: string) => {
  const i = p.lastIndexOf("/");
  return i >= 0 ? p.slice(i + 1) : p;
};

const cdnPair = (src: string) => {
  const base = fileBase(src).replace(/\.(png|jpg|jpeg|webp)$/i, "");
  return { webp: `${cdnTransparent}${base}.webp`, png: `${cdnTransparent}${base}.png` } as const;
};

// Optional derived assets (generated by pipeline): shading/ and specular/
const shadingPair = (src: string) => {
  const base = fileBase(src).replace(/\.(png|jpg|jpeg|webp)$/i, "");
  return {
    webp: `${cdnTransparent}shading/${base}.webp`,
    png: `${cdnTransparent}shading/${base}.png`,
  } as const;
};
const specularPair = (src: string) => {
  const base = fileBase(src).replace(/\.(png|jpg|jpeg|webp)$/i, "");
  return {
    webp: `${cdnTransparent}specular/${base}.webp`,
    png: `${cdnTransparent}specular/${base}.png`,
  } as const;
};
const edgesPair = (src: string) => {
  const base = fileBase(src).replace(/\.(png|jpg|jpeg|webp)$/i, "");
  return {
    webp: `${cdnTransparent}edges/${base}.webp`,
    png: `${cdnTransparent}edges/${base}.png`,
  } as const;
};

// Koristimo originalni transparent sprite kao CSS masku (WebP -> PNG fallback u listi)
const toTransparentSilhouette = (src: string) => {
  const u = cdnPair(src);
  return `url(${u.webp}), url(${u.png})`;
};

/* =====================================================================================
   Vizuelni presetovi (ton, kontrast, spekular, ivice)
===================================================================================== */

// Globalni noise (1x1 tiled PNG ~ neutral gray dots). Sprecava "plastican" izgled.
// Mali je, base64 inline (nema eksternih poziva).
const NOISE_DATA =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWMYefz/fwAI1QLS/7j4OQAAAABJRU5ErkJggg==";

type Tone = "light" | "medium" | "dark" | undefined;

// Ton-mapiranje (cuva dubinu crne, pojacava midtone, ali ne �pegla� svetla)
const toneBlend = (tone?: string) => {
  switch (tone as Tone) {
    case "dark":
      return { opacity: 1, filter: "brightness(1.04) contrast(1.20) saturate(1.12)" } as const;
    case "light":
      return { opacity: 1, filter: "brightness(1.06) contrast(1.10) saturate(1.08)" } as const;
    default:
      return { opacity: 1, filter: "brightness(1.05) contrast(1.14) saturate(1.10)" } as const;
  }
};

// Parametri za �premium� svetlo po tonu � top/bottom soft-light, edge glow, highlight
const toneVisual = (tone?: string) => {
  if (tone === "dark")
    return {
      softLightTop: 0.08,
      softLightBottom: 0.07,
      edgeGlow: 0.055,
      specular: 0.18,
      noise: 0.16,
      vignette: 0.25,
      fineDetail: 0.06,
      fineDetailSleeve: 0.04,
      detailScale: "24%",
    };
  if (tone === "light")
    return {
      softLightTop: 0.06,
      softLightBottom: 0.05,
      edgeGlow: 0.04,
      specular: 0.13,
      noise: 0.12,
      vignette: 0.18,
      fineDetail: 0.07,
      fineDetailSleeve: 0.05,
      detailScale: "26%",
    };
  return {
    softLightTop: 0.07,
    softLightBottom: 0.06,
    edgeGlow: 0.05,
    specular: 0.16,
    noise: 0.15,
    vignette: 0.21,
    fineDetail: 0.08,
    fineDetailSleeve: 0.05,
    detailScale: "25%",
  };
};

/* =====================================================================================
   Komponenta
===================================================================================== */

type Props = { config: SuitState };

export default function SuitPreview({ config }: Props) {
  const [fabrics, setFabrics] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  // Pan/zoom samo na teksturu tkanine (ne menja maske)
  const [scale, setScale] = useState(1);
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  const dragRef = useRef<{ x: number; y: number; active: boolean }>({ x: 0, y: 0, active: false });

  const currentSuit = suits.find((s) => s.id === config.styleId);
  if (!currentSuit) return null;

  useEffect(() => {
    let cancelled = false;
    const url = `${getBackendBase()}fabrics.php`;
    fetch(url, { cache: "no-store" })
      .then((r) => r.json())
      .then((data) => {
        if (!cancelled && data?.success) setFabrics(data.data);
      })
      .catch((e) => console.error("Fabrics load error", e))
      .finally(() => !cancelled && setLoading(false));
    return () => {
      cancelled = true;
    };
  }, []);

  const selectedFabric = fabrics.find((f) => String(f.id) === String(config.colorId));
  const fabricTexture = selectedFabric?.texture || "";

  const tb = toneBlend(selectedFabric?.tone);
  const vis = toneVisual(selectedFabric?.tone);

  // Solid base color by tone, used under subtle fabric weave
  const toneBaseColor = (() => {
    const t = (selectedFabric?.tone || "medium") as Tone;
    if (t === "dark") return "#2b2b2b";
    if (t === "light") return "#c8c8c8";
    return "#8f8f8f";
  })();

  // Average color from fabric texture (to better match hue)
  const [fabricAvgColor, setFabricAvgColor] = useState<string | null>(null);
  useEffect(() => {
    if (!fabricTexture) {
      setFabricAvgColor(null);
      return;
    }
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      try {
        const c = document.createElement("canvas");
        const ctx = c.getContext("2d");
        if (!ctx) return;
        const w = 32,
          h = 32;
        c.width = w;
        c.height = h;
        ctx.drawImage(img, 0, 0, w, h);
        const d = ctx.getImageData(0, 0, w, h).data;
        let r = 0,
          g = 0,
          b = 0,
          n = 0;
        for (let i = 0; i < d.length; i += 4) {
          const a = d[i + 3];
          if (a < 10) continue;
          r += d[i];
          g += d[i + 1];
          b += d[i + 2];
          n++;
        }
        if (n > 0) {
          const toHex = (x: number) => Math.max(0, Math.min(255, Math.round(x))).toString(16).padStart(2, "0");
          setFabricAvgColor(`#${toHex(r / n)}${toHex(g / n)}${toHex(b / n)}`);
        } else setFabricAvgColor(null);
      } catch {}
    };
    img.onerror = () => setFabricAvgColor(null);
    img.src = fabricTexture;
  }, [fabricTexture]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full text-gray-400 text-sm">
        Ucitavanje tkanina�
      </div>
    );
  }
  if (!selectedFabric) {
    return (
      <div className="flex items-center justify-center h-full text-gray-500 text-sm">
        Izaberi tkaninu da vidi� odelo.
      </div>
    );
  }

  /* -----------------------------------------------------------------------------
     Dinamicka zamena revera (da maska uvek prati izabrani rever)
  ----------------------------------------------------------------------------- */
  const baseLayers: SuitLayer[] = currentSuit.layers || [];
  const selectedLapel =
    currentSuit.lapels?.find((l) => l.id === config.lapelId) ?? currentSuit.lapels?.[0];
  const selectedLapelWidth =
    selectedLapel?.widths.find((w) => w.id === config.lapelWidthId) ||
    selectedLapel?.widths.find((w) => w.id === "medium") ||
    selectedLapel?.widths?.[0];

  const swapLapelInPath = (src: string, lapelType?: string, lapelWidth?: string) => {
    const type = lapelType ?? "notch";
    const width = lapelWidth ?? "medium";
    return src.replace(
      /lapel_(narrow|medium|wide)\+style_lapel_(notch|peak)/,
      `lapel_${width}+style_lapel_${type}`
    );
  };

  const suitLayers = baseLayers.map((l) =>
    l.id === "torso" ? { ...l, src: swapLapelInPath(l.src, selectedLapel?.id, selectedLapelWidth?.id) } : l
  );

  /* -----------------------------------------------------------------------------
     Opcioni slojevi (pockets/cuffs/breast pocket/interior)
  ----------------------------------------------------------------------------- */
  const pocketSrc =
    config.pocketId && currentSuit.pockets?.find((p) => p.id === config.pocketId)?.src;

  const cuffSrc =
    config.cuffId && currentSuit.cuffs?.find((c) => c.id === config.cuffId)?.src;

  const pantsPleatSrc =
    config.pantsPleatId === "double" ? "/assets/suits/blue/pleats_double.png" : undefined;

  const interiorLayers: SuitLayer[] | undefined = (() => {
    const def = currentSuit.interiors?.[0];
    const active = config.interiorId ?? def?.id;
    const found = currentSuit.interiors?.find((i) => i.id === active);
    return Array.isArray(found?.layers) ? found.layers : undefined;
  })();

  const breastPocketLayers: SuitLayer[] | undefined = (() => {
    const id = config.breastPocketId;
    const found = id ? currentSuit.breastPocket?.find((bp) => bp.id === id) : undefined;
    return Array.isArray(found?.layers) ? found.layers : undefined;
  })();

  /* -----------------------------------------------------------------------------
     Canvas konstante
  ----------------------------------------------------------------------------- */
  const JACKET_CANVAS = { w: 600, h: 733 } as const;
  const PANTS_CANVAS = { w: 600, h: 350 } as const;

  /* -----------------------------------------------------------------------------
     Helperi za tkaninu (sa pan/zoom param.)
  ----------------------------------------------------------------------------- */
  const fabricMaskStyle = (
    src: string,
    canvas: { w: number; h: number } = JACKET_CANVAS
  ): React.CSSProperties => {
    // koristimo pan/zoom nad teksturom
    const bgSize = `${Math.round(canvas.w * scale)}px ${Math.round(canvas.h * scale)}px`;
    const bgPos = `${Math.round(offset.x)}px ${Math.round(offset.y)}px`;
    return {
      backgroundImage: `url(${fabricTexture})`,
      backgroundSize: bgSize,
      backgroundPosition: bgPos,
      backgroundRepeat: "repeat", // dozvoljavamo ponavljanje zbog weave obrazaca
      opacity: tb.opacity,
      filter: tb.filter,
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  // Solid color fill under the weave, same mask
  const colorBaseMaskStyle = (
    src: string
  ): React.CSSProperties => {
    return {
      backgroundColor: fabricAvgColor || toneBaseColor,
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  // Subtle weave overlay on top of solid base (reduced visibility)
  const fabricWeaveOverlayStyle = (
    src: string,
    canvas: { w: number; h: number } = JACKET_CANVAS
  ): React.CSSProperties => {
    const bgSize = `${Math.round(canvas.w * scale)}px ${Math.round(canvas.h * scale)}px`;
    const bgPos = `${Math.round(offset.x)}px ${Math.round(offset.y)}px`;
    const t = (selectedFabric?.tone || "medium") as Tone;
    const op = t === "dark" ? 0.14 : t === "light" ? 0.20 : 0.17;
    return {
      backgroundImage: `url(${fabricTexture})`,
      backgroundSize: bgSize,
      backgroundPosition: bgPos,
      backgroundRepeat: "repeat",
      opacity: op,
      mixBlendMode: "soft-light",
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  // Unified fabric base across multiple layers to avoid seams (e.g., torso + sleeves)
  const unifiedFabricBaseStyle = (layers: SuitLayer[], canvas: { w: number; h: number }) => {
    const bgSize = `${Math.round(canvas.w * scale)}px ${Math.round(canvas.h * scale)}px`;
    const bgPos = `${Math.round(offset.x)}px ${Math.round(offset.y)}px`;

    const maskImages: string[] = [];
    const maskSizes: string[] = [];
    const maskRepeats: string[] = [];
    const maskPositions: string[] = [];
    for (const L of layers) {
      const u = cdnPair(L.src);
      // WebP first, PNG fallback
      maskImages.push(`url(${u.webp})`);
      maskImages.push(`url(${u.png})`);
      maskSizes.push("contain", "contain");
      maskRepeats.push("no-repeat", "no-repeat");
      maskPositions.push("center", "center");
    }

    const t = (selectedFabric?.tone || "medium") as Tone;
    const weaveOpacity = t === "dark" ? 0.14 : t === "light" ? 0.20 : 0.17;

    return {
      // Solid tint from sampled fabric color
      backgroundColor: fabricAvgColor || toneBaseColor,
      // Underlay weave as second background via pseudo pattern on sibling; simpler: add a separate overlay below per-part layers
      WebkitMaskImage: maskImages.join(", "),
      WebkitMaskRepeat: maskRepeats.join(", "),
      WebkitMaskSize: maskSizes.join(", "),
      WebkitMaskPosition: maskPositions.join(", "),
      maskImage: maskImages.join(", "),
      maskRepeat: maskRepeats.join(", "),
      maskSize: maskSizes.join(", "),
      maskPosition: maskPositions.join(", "),
    } as React.CSSProperties;
  };

  // Unified weave overlay across provided layers (prevents visible weave seams)
  const unifiedWeaveOverlayStyle = (layers: SuitLayer[], canvas: { w: number; h: number }) => {
    const bgSize = `${Math.round(canvas.w * scale)}px ${Math.round(canvas.h * scale)}px`;
    const bgPos = `${Math.round(offset.x)}px ${Math.round(offset.y)}px`;

    const maskImages: string[] = [];
    const maskSizes: string[] = [];
    const maskRepeats: string[] = [];
    const maskPositions: string[] = [];
    for (const L of layers) {
      const u = cdnPair(L.src);
      maskImages.push(`url(${u.webp})`, `url(${u.png})`);
      maskSizes.push("contain", "contain");
      maskRepeats.push("no-repeat", "no-repeat");
      maskPositions.push("center", "center");
    }

    const t = (selectedFabric?.tone || "medium") as Tone;
    const opacity = t === "dark" ? 0.14 : t === "light" ? 0.20 : 0.17;

    return {
      backgroundImage: `url(${fabricTexture})`,
      backgroundSize: bgSize,
      backgroundPosition: bgPos,
      backgroundRepeat: "repeat",
      mixBlendMode: "soft-light",
      opacity,
      WebkitMaskImage: maskImages.join(", "),
      WebkitMaskRepeat: maskRepeats.join(", "),
      WebkitMaskSize: maskSizes.join(", "),
      WebkitMaskPosition: maskPositions.join(", "),
      maskImage: maskImages.join(", "),
      maskRepeat: maskRepeats.join(", "),
      maskSize: maskSizes.join(", "),
      maskPosition: maskPositions.join(", "),
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  // Feather the inner sleeve seam so torso/sleeve transition is invisible
  const sleevesFeatherStyle: React.CSSProperties = {
    background:
      `linear-gradient(90deg, rgba(255,255,255,0.06), rgba(255,255,255,0) 14%),` +
      `linear-gradient(270deg, rgba(255,255,255,0.06), rgba(255,255,255,0) 14%)`,
    mixBlendMode: "soft-light",
    opacity: 0.7,
    pointerEvents: "none",
  };

  // Bring back baked folds/highlights from transparent base sprite (alpha PNG/WebP)
  const baseSpriteOverlayStyle = (
    src: string,
    blend: 'multiply' | 'soft-light' | 'overlay' = 'multiply',
    opacity = 0.35
  ): React.CSSProperties => {
    const u = cdnPair(src);
    return {
      backgroundImage: `url(${u.webp}), url(${u.png})`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "contain",
      backgroundPosition: "center",
      mixBlendMode: blend,
      opacity,
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  // Shading/specular overlays (auto-use if files exist on CDN)
  const shadingOverlayStyle = (
    src: string,
    opacity = 0.22
  ): React.CSSProperties => {
    const u = shadingPair(src);
    return {
      backgroundImage: `url(${u.webp}), url(${u.png})`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "contain",
      backgroundPosition: "center",
      mixBlendMode: "multiply",
      opacity,
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  const specularOverlayStyle = (
    src: string,
    opacity = 0.16
  ): React.CSSProperties => {
    const u = specularPair(src);
    return {
      backgroundImage: `url(${u.webp}), url(${u.png})`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "contain",
      backgroundPosition: "center",
      mixBlendMode: "overlay",
      opacity,
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
      filter: "saturate(1.02)",
    } as React.CSSProperties;
  };
  const edgesOverlayStyle = (
    src: string,
    opacity = 0.38
  ): React.CSSProperties => {
    const u = edgesPair(src);
    return {
      backgroundImage: `url(${u.webp}), url(${u.png})`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "contain",
      backgroundPosition: "center",
      mixBlendMode: "multiply",
      opacity,
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
      filter: "contrast(1.1)",
    } as React.CSSProperties;
  };

  // �Fine detail� overlay koristi istu teksturu, ali sitniji scale i drugaciji blend
  const fineDetailStyle = (
    src: string,
    opacity: number,
    size: string,
    canvas: { w: number; h: number }
  ): React.CSSProperties => {
    return {
      backgroundImage: `url(${fabricTexture})`,
      backgroundRepeat: "repeat",
      backgroundSize: size,
      backgroundPosition: "center",
      opacity,
      mixBlendMode: "soft-light",
      filter: "contrast(1.04)",
      WebkitMaskImage: toTransparentSilhouette(src),
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "contain",
      WebkitMaskPosition: "center",
      maskImage: toTransparentSilhouette(src),
      maskRepeat: "no-repeat",
      maskSize: "contain",
      maskPosition: "center",
      pointerEvents: "none",
    } as React.CSSProperties;
  };

  /* -----------------------------------------------------------------------------
     Pan/zoom handlers
  ----------------------------------------------------------------------------- */
  const onWheel: React.WheelEventHandler<HTMLDivElement> = (e) => {
    e.preventDefault();
    const delta = -e.deltaY;
    setScale((s) => Math.min(3, Math.max(1, s + delta * 0.0015)));
  };
  const onMouseDown: React.MouseEventHandler<HTMLDivElement> = (e) => {
    dragRef.current = { x: e.clientX - offset.x, y: e.clientY - offset.y, active: true };
  };
  const onMouseMove: React.MouseEventHandler<HTMLDivElement> = (e) => {
    if (!dragRef.current.active) return;
    setOffset({ x: e.clientX - dragRef.current.x, y: e.clientY - dragRef.current.y });
  };
  const onMouseUp: React.MouseEventHandler<HTMLDivElement> = () => {
    if (dragRef.current.active) dragRef.current.active = false;
  };

  /* -----------------------------------------------------------------------------
     Render redosled
  ----------------------------------------------------------------------------- */
  const pants = suitLayers.find((l) => l.id === "pants");
  const bodyLayers = suitLayers.filter((l) => l.id !== "pants");

  /* -----------------------------------------------------------------------------
     Simulirani shading/specular bez foldera:
     - global vignette (multiply)
     - top/bottom soft-light tok
     - centralni vertical specular (overlay)
     - edge glow (soft-light)
     - micro-noise (overlay)
     - per-part dodatni gradijenti (rukavi, ramena, rever)
  ----------------------------------------------------------------------------- */
  // Global overlays uklonjeni sa canvas-a da ne prave pozadinski halo izvan maske.
  // Zadr�avamo per-part naglaske i generisane mape.

  // Per-part naglasci (ramena/rukavi + rever)
  const TorsoLapelEmphasis: React.FC = () => (
    <div
      className="absolute inset-0 pointer-events-none"
      style={{
        background:
          // V senka ka dugmetu + blage dijagonalne svetle ivice revera
          `radial-gradient(80% 80% at 50% 12%, rgba(0,0,0,0.06), rgba(0,0,0,0) 45%),` +
          `linear-gradient(135deg, rgba(255,255,255,0.05), rgba(255,255,255,0) 25%),` +
          `linear-gradient(225deg, rgba(255,255,255,0.05), rgba(255,255,255,0) 25%)`,
        mixBlendMode: "soft-light",
      }}
    />
  );

  const SleeveShoulderEmphasis: React.FC = () => (
    <div
      className="absolute inset-0 pointer-events-none"
      style={{
        background:
          // Blagi highlight po ramenima + zasencenje ka laktu
          `radial-gradient(60% 40% at 20% 5%, rgba(255,255,255,0.06), rgba(255,255,255,0) 60%),` +
          `radial-gradient(60% 40% at 80% 5%, rgba(255,255,255,0.06), rgba(255,255,255,0) 60%),` +
          `linear-gradient(180deg, rgba(0,0,0,0.05), rgba(0,0,0,0) 30%, rgba(0,0,0,0.05) 60%, rgba(0,0,0,0) 85%)`,
        mixBlendMode: "soft-light",
      }}
    />
  );

  /* =====================================================================================
     RENDER
  ====================================================================================== */
  return (
    <div className="w-full select-none bg-white">
      {/* ======================== JACKET CANVAS ======================== */}
      <div
        className="relative mx-auto"
        style={{ width: "100%", aspectRatio: "600 / 733", maxWidth: 720 }}
        onWheel={onWheel}
        onMouseDown={onMouseDown}
        onMouseMove={onMouseMove}
        onMouseUp={onMouseUp}
        onMouseLeave={onMouseUp}
      >
        {/* Interiors (ispod tkanine) */}
        {interiorLayers?.map((l) => (
          <img
            key={`int-${l.id}`}
            src={l.src}
            alt={l.name}
            className="absolute inset-0 w-full h-full object-contain pointer-events-none"
          />
        ))}

        {/* Opcioni �shirt� izmedu interiora i tkanine */}
        {config.showShirt && (
          <img
            src={`${cdnTransparent}shirt_to_jacket_open.png`}
            onError={(e) => {
              const local = "/assets/suits/transparent/shirt_to_jacket_open.png";
              if (e.currentTarget.src !== local) e.currentTarget.src = local;
            }}
            alt="Shirt"
            className="absolute inset-0 w-full h-full object-contain pointer-events-none"
          />
        )}

        {/* Unified fabric base (torso + sleeves + bottom) to remove seams */}
      <div
          className="absolute inset-0"
          style={unifiedFabricBaseStyle(
            suitLayers.filter((x) => x.id === "torso" || x.id === "sleeves" || x.id === "bottom"),
            JACKET_CANVAS
          )}
        />
        <div
          className="absolute inset-0"
          style={unifiedWeaveOverlayStyle(
            suitLayers.filter((x) => x.id === "torso" || x.id === "sleeves" || x.id === "bottom"),
            JACKET_CANVAS
          )}
        />

        {/* BODY LAYERS (torzo, rukavi, donji deo) */}
        {suitLayers
          .filter((l) => l.id !== "pants")
          .map((l) => (
            <div key={l.id} className="absolute inset-0">
              {/* Blagi "wash" za mekoću (umeren, ujednačen) */}
              <div
                className="absolute inset-0"
                style={{
                  ...fabricMaskStyle(l.src, JACKET_CANVAS),
                  opacity: 0.08,
                  filter: `${tb.filter} blur(3px) saturate(1.02)`,
                }}
              />
              {/* Reintroduce baked sprite details (shadows/folds) */}
              <div className="absolute inset-0" style={baseSpriteOverlayStyle(l.src, 'multiply', l.id === 'sleeves' ? 0.18 : 0.30)} />
              <div className="absolute inset-0" style={baseSpriteOverlayStyle(l.src, 'soft-light', l.id === 'sleeves' ? 0.10 : 0.16)} />
              {l.id === 'sleeves' && (
                <div className="absolute inset-0" style={sleevesFeatherStyle} />
              )}
              {/* Fine detail (sitni weave refleksi) */}
              <div
                className="absolute inset-0"
                style={{
                  ...fineDetailStyle(
                    l.src,
                    l.id === "sleeves" ? vis.fineDetailSleeve : vis.fineDetail,
                    vis.detailScale,
                    JACKET_CANVAS
                  ),
                }}
              />
              {/* Generated shading/specular (ako postoje na CDN-u) */}
              <div
                className="absolute inset-0"
                style={shadingOverlayStyle(
                  l.src,
                  l.id === 'sleeves'
                    ? (selectedFabric?.tone === "dark" ? 0.10 : selectedFabric?.tone === "light" ? 0.07 : 0.09)
                    : (selectedFabric?.tone === "dark" ? 0.18 : selectedFabric?.tone === "light" ? 0.13 : 0.16)
                )}
              />
              <div
                className="absolute inset-0"
                style={specularOverlayStyle(
                  l.src,
                  l.id === 'sleeves'
                    ? (selectedFabric?.tone === "dark" ? 0.08 : selectedFabric?.tone === "light" ? 0.06 : 0.07)
                    : (selectedFabric?.tone === "dark" ? 0.13 : selectedFabric?.tone === "light" ? 0.10 : 0.12)
                )}
              />
              {/* Edges/Seams definition (mekše na rukavima da ne pravi liniju) */}
              <div className="absolute inset-0" style={edgesOverlayStyle(l.src, l.id === 'sleeves' ? 0.14 : (l.id === 'bottom' ? 0.10 : 0.20))} />
              {/* Per-part naglasci */}
              {l.id === "torso" && <TorsoLapelEmphasis />}
              {l.id === "sleeves" && <SleeveShoulderEmphasis />}
            </div>
          ))}

        {/* Opcioni d�epovi (fabric-masked) */}
        {pocketSrc && (
          <div className="absolute inset-0">
            <div className="absolute inset-0" style={{ ...colorBaseMaskStyle(pocketSrc) }} />
            <div className="absolute inset-0" style={{ ...fabricWeaveOverlayStyle(pocketSrc, JACKET_CANVAS) }} />
            <div className="absolute inset-0" style={baseSpriteOverlayStyle(pocketSrc, 'multiply', 0.28)} />
            {/* Mikro kontrast na rubovima d�epova */}
            <div
              className="absolute inset-0 pointer-events-none"
              style={{
                background:
                  "linear-gradient(180deg, rgba(0,0,0,0.10), rgba(0,0,0,0) 20%, rgba(0,0,0,0) 80%, rgba(0,0,0,0.10))",
                mixBlendMode: "multiply",
                opacity: 0.18,
                WebkitMaskImage: toTransparentSilhouette(pocketSrc),
                WebkitMaskRepeat: "no-repeat",
                WebkitMaskSize: "contain",
                WebkitMaskPosition: "center",
                maskImage: toTransparentSilhouette(pocketSrc),
                maskRepeat: "no-repeat",
                maskSize: "contain",
                maskPosition: "center",
              }}
            />
            {/* Shading/specular za d�epove (ako postoje) */}
            <div className="absolute inset-0" style={shadingOverlayStyle(pocketSrc, 0.18)} />
            <div className="absolute inset-0" style={specularOverlayStyle(pocketSrc, 0.12)} />
          </div>
        )}

        {/* Breast pocket (ako postoji set slojeva) */}
        {breastPocketLayers?.map((l) => (
          <React.Fragment key={`bp-${l.id}`}>
            <div className="absolute inset-0" style={{ ...colorBaseMaskStyle(l.src) }} />
            <div className="absolute inset-0" style={{ ...fabricWeaveOverlayStyle(l.src, JACKET_CANVAS) }} />
            <div className="absolute inset-0" style={baseSpriteOverlayStyle(l.src, 'multiply', 0.26)} />
            <div
              className="absolute inset-0 pointer-events-none"
              style={{
                background:
                  "linear-gradient(180deg, rgba(0,0,0,0.10), rgba(0,0,0,0) 25%, rgba(0,0,0,0) 75%, rgba(0,0,0,0.10))",
                mixBlendMode: "multiply",
                opacity: 0.16,
                WebkitMaskImage: toTransparentSilhouette(l.src),
                WebkitMaskRepeat: "no-repeat",
                WebkitMaskSize: "contain",
                WebkitMaskPosition: "center",
                maskImage: toTransparentSilhouette(l.src),
                maskRepeat: "no-repeat",
                maskSize: "contain",
                maskPosition: "center",
              }}
            />
            <div className="absolute inset-0" style={shadingOverlayStyle(l.src, 0.16)} />
            <div className="absolute inset-0" style={specularOverlayStyle(l.src, 0.11)} />
          </React.Fragment>
        ))}

        {/* Global overlays uklonjeni da ne stvaraju pozadinski halo */}
      </div>

      {/* ======================== PANTS CANVAS ======================== */}
      {pants && (
        <div
          className="relative mx-auto mt-2"
          style={{ width: "100%", aspectRatio: "600 / 350", maxWidth: 720 }}
        >
          {/* Blagi wash */}
          <div
            className="absolute inset-0"
            style={{
              ...fabricMaskStyle(pants.src, PANTS_CANVAS),
              opacity: 0.16,
              filter: `${tb.filter} blur(3px) saturate(1.02)`,
            }}
          />
          {/* Solid base color + subtle weave */}
          <div className="absolute inset-0" style={{ ...colorBaseMaskStyle(pants.src) }} />
          <div className="absolute inset-0" style={{ ...fabricWeaveOverlayStyle(pants.src, PANTS_CANVAS) }} />
          <div className="absolute inset-0" style={baseSpriteOverlayStyle(pants.src, 'multiply', 0.45)} />
          <div className="absolute inset-0" style={baseSpriteOverlayStyle(pants.src, 'soft-light', 0.20)} />
          {/* Fine weave detalj */}
          <div
            className="absolute inset-0"
            style={{
              ...fineDetailStyle(pants.src, Math.max(0, vis.fineDetail - 0.04), vis.detailScale, PANTS_CANVAS),
              filter: "contrast(1.03)",
            }}
          />
          {/* Shading/specular za pantalone (ako postoje) */}
          <div
            className="absolute inset-0"
            style={shadingOverlayStyle(
              pants.src,
              selectedFabric?.tone === "dark" ? 0.24 : selectedFabric?.tone === "light" ? 0.16 : 0.20
            )}
          />
          <div
            className="absolute inset-0"
            style={specularOverlayStyle(
              pants.src,
              selectedFabric?.tone === "dark" ? 0.14 : selectedFabric?.tone === "light" ? 0.10 : 0.12
            )}
          />
          {/* Per-part dubina pantalona (senka pri pojasu + na dnu) */}
          <div
            className="absolute inset-0 pointer-events-none"
            style={{
              background:
                `linear-gradient(180deg, rgba(0,0,0,0.07), rgba(0,0,0,0) 35%),` +
                `linear-gradient(0deg, rgba(0,0,0,0.06), rgba(0,0,0,0) 65%)`,
              mixBlendMode: "multiply",
              WebkitMaskImage: toTransparentSilhouette(pants.src),
              WebkitMaskRepeat: "no-repeat",
              WebkitMaskSize: "contain",
              WebkitMaskPosition: "center",
              maskImage: toTransparentSilhouette(pants.src),
              maskRepeat: "no-repeat",
              maskSize: "contain",
              maskPosition: "center",
            }}
          />

          {/* Cuffs (opciono) */}
          {cuffSrc && (
            <>
              <div className="absolute inset-0" style={{ ...colorBaseMaskStyle(cuffSrc) }} />
              <div className="absolute inset-0" style={{ ...fabricWeaveOverlayStyle(cuffSrc, PANTS_CANVAS) }} />
              <div className="absolute inset-0" style={baseSpriteOverlayStyle(cuffSrc, 'multiply', 0.26)} />
              <div
                className="absolute inset-0 pointer-events-none"
                style={{
                  background:
                    "linear-gradient(180deg, rgba(0,0,0,0.12), rgba(0,0,0,0) 40%, rgba(0,0,0,0) 60%, rgba(0,0,0,0.12))",
                  mixBlendMode: "multiply",
                  opacity: 0.16,
                  WebkitMaskImage: toTransparentSilhouette(cuffSrc),
                  WebkitMaskRepeat: "no-repeat",
                  WebkitMaskSize: "contain",
                  WebkitMaskPosition: "center",
                  maskImage: toTransparentSilhouette(cuffSrc),
                  maskRepeat: "no-repeat",
                  maskSize: "contain",
                  maskPosition: "center",
                }}
              />
              <div className="absolute inset-0" style={shadingOverlayStyle(cuffSrc, 0.16)} />
              <div className="absolute inset-0" style={specularOverlayStyle(cuffSrc, 0.11)} />
            </>
          )}

          {/* Pleats (png overlay, bez maske) */}
          {pantsPleatSrc && (
            <img
              src={pantsPleatSrc}
              alt="Pleats"
              className="absolute inset-0 w-full h-full object-contain pointer-events-none"
            />
          )}

          {/* Global premium overlays (za pantalone) */}
          
        </div>
      )}
    </div>
  );
}

